//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string VIN { get; set; }
        public string RegistrationNymber { get; set; }
        public int CreationYear { get; set; }
        public int CarModelID { get; set; }
        public string Owner { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
