//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.Car = new HashSet<Car>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int CarMarkID { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual CarMark CarMark { get; set; }
    }
}
