//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSSEntities : DbContext
    {
        public TSSEntities()
            : base("name=TSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Car { get; set; }
        public DbSet<CarMark> CarMark { get; set; }
        public DbSet<CarModel> CarModel { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderService> OrderService { get; set; }
        public DbSet<OrderSpareParts> OrderSpareParts { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<Positon> Positon { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<ServiceCategory> ServiceCategory { get; set; }
        public DbSet<SparePart> SparePart { get; set; }
        public DbSet<SparePartCategory> SparePartCategory { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<Worker> Worker { get; set; }
    }
}
