//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderService = new HashSet<OrderService>();
            this.OrderSpareParts = new HashSet<OrderSpareParts>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int ReceiverID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CarVIN { get; set; }
        public int CarMileage { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<OrderService> OrderService { get; set; }
        public virtual ICollection<OrderSpareParts> OrderSpareParts { get; set; }
    }
}
