//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public string UTN { get; set; }
        public string Title { get; set; }
        public string Bank { get; set; }
        public string CheckingAccount { get; set; }
        public double VAT { get; set; }
        public string Contacts { get; set; }
        public string Address { get; set; }
    }
}
