//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positon
    {
        public Positon()
        {
            this.Worker = new HashSet<Worker>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Worker> Worker { get; set; }
    }
}
