//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.OrderService = new HashSet<OrderService>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public double PerfomanceTime { get; set; }
        public int ServiceCategoryID { get; set; }
    
        public virtual ICollection<OrderService> OrderService { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
    }
}
