//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal CostOfHour { get; set; }
    
        public virtual ICollection<Service> Service { get; set; }
    }
}
