//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePart
    {
        public SparePart()
        {
            this.OrderSpareParts = new HashSet<OrderSpareParts>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int SparePartsCategoryID { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> UnitID { get; set; }
    
        public virtual ICollection<OrderSpareParts> OrderSpareParts { get; set; }
        public virtual SparePartCategory SparePartCategory { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
