//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServiceStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Order = new HashSet<Order>();
            this.OrderService = new HashSet<OrderService>();
        }
    
        public int ID { get; set; }
        public int PositionID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PatronymicName { get; set; }
        public string PassportNumber { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<OrderService> OrderService { get; set; }
        public virtual Positon Positon { get; set; }
    }
}
